qin-todo-e-team/qin_gorilla_todo

- .eslintrc.js
- .storybook/main.js
- .storybook/preview.js
- package.json
- src/component/ExampleButton/Button.stories.tsx
- src/component/ExampleButton/Button.tsx
- src/component/ExampleButton/button.css
- yarn.lock
storybookの導入
```
yarn install
yarn storybook
```
```
localhost:6006
```
#8 
詳しくは明日共有します
> feat: storybook導入

- .firebaserc
- .gitignore
- README.md
- firebase.json
- firestore.indexes.json
- firestore.rules
- package.json
#13 
・Firebaseのエミュレータ導入
・firebase-cliをインストール
・firebaseにログイン( firebase login )
・Java(JDK)をインストール
・yarn emulator
・localhost:6671 にアクセス
もしかしたら、自分のfirebaseプロジェクトを作らないといけないかもしれないです。
詰まった場合はお気軽に連絡ください。
> feat: firebase emulator導入

- src/models/Todo.ts
- src/models/User.ts
> feat: モデルを作成

- package.json
- yarn.lock
> build: firebaseインストール

- .gitignore
- config/firebase.ts
- package.json
- yarn.lock
> feat: firebaseConfig追加

- .eslintrc.js
- config/firebase.ts
- package.json
- pages/_app.tsx
- pages/login.tsx
- src/pages/login/index.tsx
- yarn.lock
Googleログイン機能の実装
1. /loginにアクセス
2. ボタンを押下し自分のGoogleアカウントでログイン
3. Authenticationでアカウントが登録されていることを確認
> feat: ログイン機能実装

- src/component/Panel/PostPanel.tsx
- src/lib/getExpireDate.ts
- src/repository/todo/todoCollection.ts
- src/repository/todo/useTodo.ts
- tsconfig.json
https://github.com/qin-todo-e-team/qin_gorilla_todo/issues/39
PostPanelからfirebaseにTodoを追加する機能を実装
追加する処理はrepository/todo/useTodoにまとめました
テキストボックスに入力して、ボタンを押すとfirestoreに反映されます。
反映先はuser毎のtodosに追加されるため、現時点での動作確認はfirebaseを参照する形でお願いします！
https://console.firebase.google.com/project/singolliratodo/firestore/data/~2Fuser~2Fundefined~2Ftodos~2FcgplNbAis9bSx7YbmVdR
> feat: PostPanelからfirebaseにTodoを追加する機能を実装

- .eslintrc.js
- config/firebase.ts
- pages/_app.tsx
- pages/account/[userId]/accountSetting/index.tsx
- src/component/accountSetting/AccountSetting.tsx
- src/component/accountSetting/SelectRow/index.tsx
- src/component/accountSetting/index.tsx
アカウント設定のUI実装
1. /account/1/accountSettingにアクセス
2. ログアウトボタンまたはアカウントの削除ボタンを押下しモーダルが出ることを確認
https://user-images.githubusercontent.com/77882967/155882952-886ae8d8-5904-4689-a0d0-9167987674e0.mov
> feat: アカウント設定のUI実装

- config/firebase.ts
- pages/_app.tsx
- src/component/accountSetting/AccountSetting.tsx
- src/context/AuthContext.tsx
- src/pages/login/index.tsx
ログアウト及びアカウント削除機能実装
1. /loginにアクセス
2. ボタンを押下し自分のGoogleアカウントでログイン
3. Authenticationでアカウントが登録されていることを確認
4. /account/1/accountSettingにアクセス
5. ログアウトボタンを押下しモーダル中のOKボタンを押下 (ログアウト完了)
6. 再度ログイン
7. /account/1/accountSettingにアクセス
8. アカウントの削除ボタンを押下しモーダル中のOKボタンを押下 (アカウント削除完了)
9. Authenticationでアカウントが削除されていることを確認
https://user-images.githubusercontent.com/77882967/156015151-bef1423d-06a7-4dc4-b171-fc198289217b.mov
> feat: ログアウト及びアカウント削除機能実装

- config/theme.ts
- pages/_document.tsx
- src/component/Theme/SelectRow/index.tsx
- src/lib/setThemeColor.ts
- src/provider/ThemeProvider.tsx
system colorが選べるように実装
https://user-images.githubusercontent.com/67675670/156564881-dac7a504-b955-476d-9530-41b34d295b99.mov
~~https://github.com/qin-todo-e-team/qin_gorilla_todo/pull/44
こっちがマージされたら確認~~
> feat: system colorを選べる実装

- .eslintrc.js
- src/component/Theme/Theme.tsx
- src/models/Theme.ts
表題通り
eslintのcamelCaseルールを除外しました。
(const assertionの大文字でエラーが吐かれていたため)
> refactor: テーマをModelとして切り出し

- src/component/Panel/PostButton.tsx
- src/component/Panel/PostPanel.tsx
- src/pages/index/index.tsx
[ ] firebase rules のデプロイ
[ ] PR に label を貼る
[ ] PR に Reviewer を Assign する
[ ] PR の Assignee を自分をにする
> refactor: PostPanelとPostButtonのリファクタ

- src/pages/[userId]/todo/index.tsx
[ ] firebase rules のデプロイ
[ ] PR に label を貼る
[ ] PR に Reviewer を Assign する
[ ] PR の Assignee を自分をにする
> fix: PostPanelの修正

- package.json
- src/component/Theme/SelectRow/index.tsx
- src/pages/[userId]/account/profile/index.tsx
- src/pages/[userId]/account/theme/index.tsx
- src/pages/[userId]/todo/index.tsx
- src/repository/profile/useProfile.ts
- src/repository/toast/useToast.ts
- src/repository/todo/useTodo.ts
- yarn.lock
#68 
React hot toastを導入しました！
以下の変更のポップアップに適応しています。
- Todoの追加、変更、削除
- Themeの設定変更
- Profileの設定変更
https://user-images.githubusercontent.com/15701307/157933533-b9e3b1dd-0b02-4739-b1cf-786e1da1d063.mov
> feat: react-hot-toastの導入 #68

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
release-drafterワークフロー追加
リリースノートを自動作成してくれるワークフローを追加しました。
参考:
https://blog.kondoumh.com/entry/2021/03/26/151425
> feat: release-drafter追加

- src/component/CheckBox/CheckBox.tsx
- src/component/Panel/PostPanel.tsx
- src/component/TodoList/TodoList.tsx
- src/context/TodoContext.tsx
- src/lib/TodoFilter.ts
- src/pages/[userId]/todo/index.tsx
- tsconfig.json
#74 
Todoを選択した際に、TextBoxへ選択したTodoを電波させるように追加しました。
更新処理は修正していないので、新規追加という形になっているため、適時修正してもらえたらと思います。
https://user-images.githubusercontent.com/67675670/158047444-8a5b69c5-f99d-420f-bb64-b05982017ce8.mov
> feat: todoContext追加（下地のみ）

- src/component/Theme/SelectRow/index.tsx
themeに失敗時のエラーハンドリングがされていなかったのでハンドリングを追加
> fix: themeのエラーハンドリング

- .github/release-drafter.yml
> fix: commitのtitleでもラベルがつくように修正

- src/lib/TodoFilter.ts
> fix: TodoFilterで正常に分類されない問題に対応

- config/firebase.ts
- src/component/accountSetting/AccountSetting.tsx
アカウントの削除後に画面遷移しない問題に対応
http://localhost:3000/{userId}/account/accountSetting
> fix: アカウントの削除後に画面遷移しない問題に対応
